extends: site.yaml

mode: production

deploy_root: deploy_production

publisher:
    github:
        type: hyde.ext.publishers.dvcs.Git
        path: ../ajdawson.github.io
        url: git@github.com:ajdawson/ajdawson.github.io.git
